### PR TITLE
chore: Update list 03/12/19

### PR DESCRIPTION
**Pull request by Richienb**
This PR updates the list of TLDs.

Also, we should probably be using a build service like Travis CI to automatically build the list.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
> Also, we should probably be using a build service like Travis CI to automatically build the list.

Agreed! For awhile, @TooTallNate had a CRON setup to manage this. I think a GitHub Action could do the trick pretty easily tho.

**Comment by stephenmathieson** [comment]
Released as **1.207.0**.

**Comment by Richienb** [comment]
@stephenmathieson I've got a bit of spare time to set up the GitHub Action. Please add me as a collaborator. For automatically publishing to NPM, please run `npm owner add Richienb tlds` or provide an NPM token of your own.

**Comment by TooTallNate** [comment]
I'm not sure what happened to my cronjob. Something with SSH keys haha. I haven't logged into that DO box in a long time. GH Actions or CircleCI does indeed seem to be the more proper approach to this nowadays (this cronjob was one of the two reasons I even keep the DO box around, sill be nice to shut it down soon).

**Comment by stephenmathieson** [comment]
I messed with CircleCI briefly yesterday in attempt to get a daily build setup. Doesn't seem like it worked tho :man_shrugging: 

@Richienb I'll add you shortly. Thanks for offering :)

**Comment by stephenmathieson** [comment]
@Richienb just tried to add you on npm but ran into an error:

```
∴ npm owner add Richienb tlds
npm ERR! owner mutate Error getting user data for Richienb
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/-/user/org.couchdb.user:Richienb

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2019-12-04T15_00_48_825Z-debug.log
```

Looks like you gave me the wrong username?

I did add you as a collaborator on GitHub tho! Let me know when you want review of the action 😄

**Comment by Richienb** [comment]
@stephenmathieson Try `richienb` instead of `Richienb`.

**Comment by Richienb** [comment]
Development started on the [`new`](https://github.com/stephenmathieson/node-tlds/tree/new) branch.

**Pull request merged**
